### ISSUE TITLE
cant run android fundamentals pps 

### ISSUE THREAD

**Issue by azizhadisaleh** [google-developer-training/android-fundamentals#8]
i have opened android-fundamentals in my android studio and installed all required tools but finaly cant run any app. how can solve this problem: 

**Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation' and 'testApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html**

**Comment by jhansi** [comment]
Thank you for reporting the issue. 

But this is just a warning not an error, you should still be able to run the apps. Try deploying the app on to a device or an emulator and check again.   

We will address this issue in our next update and make sure you don't see this warning.
